from enum import Enum

class AppendicesParseType(Enum):
    NOTING = 1
    SECURITY_EVENTS = 2
    STANDARDIZED_UNITS_OF_MEASURE = 3
    SUMMARY_LIST_OF_STANDARDIZED_COMPONENTS = 4
    STANDARDIZED_VARIABLES = 5
    TABLE_OF_CONTENTS = 6