version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "2181" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  kafka:
    image: confluentinc/cp-kafka:7.2.1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    restart: always
  db:
    restart: always
    image: mysql:5.7
    privileged: true
    ports:
      - "4000:3306"
    environment:
      MYSQL_DATABASE: ocpp_test
      MYSQL_ROOT_PASSWORD: 12er34qw
      TZ: "Asia/Seoul"
    volumes:
      - ./dataset/mysql_initdb:/docker-entrypoint-initdb.d:ro
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    networks:
      - default
    container_name: db